#compdef pm
# Zsh completion for pm CLI tool
#
# Installation:
#   Copy to a directory in $fpath (e.g., /usr/local/share/zsh/site-functions/)
#   or source directly in ~/.zshrc:
#     source /path/to/pm-completion.zsh
#
# Auto-generated by Click. To regenerate:
#   _PM_COMPLETE=zsh_source pm > pm-completion.zsh

_pm_completion() {
    local -a completions
    local -a completions_with_descriptions
    local -a response
    (( ! $+commands[pm] )) && return 1

    response=("${(@f)$(env COMP_WORDS="${words[*]}" COMP_CWORD=$((CURRENT-1)) _PM_COMPLETE=zsh_complete pm)}")

    for type key descr in ${response}; do
        if [[ "$type" == "plain" ]]; then
            if [[ "$descr" == "_" ]]; then
                completions+=("$key")
            else
                completions_with_descriptions+=("$key":"$descr")
            fi
        elif [[ "$type" == "dir" ]]; then
            _path_files -/
        elif [[ "$type" == "file" ]]; then
            _path_files -f
        fi
    done

    if [ -n "$completions_with_descriptions" ]; then
        _describe -V unsorted completions_with_descriptions -U
    fi

    if [ -n "$completions" ]; then
        compadd -U -V unsorted -a completions
    fi
}

compdef _pm_completion pm
