#!/bin/bash
# Bash completion for pm CLI tool
#
# Installation:
#   On Linux: Copy to /etc/bash_completion.d/ or ~/.bash_completion
#   On macOS: Copy to /usr/local/etc/bash_completion.d/
#
# Or source directly in ~/.bashrc:
#   source /path/to/pm-completion.bash
#
# Auto-generated by Click. To regenerate:
#   _PM_COMPLETE=bash_source pm > pm-completion.bash

_pm_completion() {
    local IFS=$'\n'
    local response

    response=$(env COMP_WORDS="${COMP_WORDS[*]}" COMP_CWORD=$COMP_CWORD _PM_COMPLETE=bash_complete $1)

    for completion in $response; do
        IFS=',' read type value <<< "$completion"

        if [[ $type == 'dir' ]]; then
            COMPREPLY=()
            compopt -o dirnames
        elif [[ $type == 'file' ]]; then
            COMPREPLY=()
            compopt -o default
        elif [[ $type == 'plain' ]]; then
            COMPREPLY+=($value)
        fi
    done

    return 0
}

complete -o nosort -F _pm_completion pm
